export const KOREAN_FIELDWORK_CATEGORIES = {
  AERIAL_MAP_LAYER: 'AerialMapLayer',
  DAILY_LOG: 'DailyLog',
  DRAWING: 'Drawing',
  FEATURE: 'Feature',
  FEATURE_GROUP: 'FeatureGroup',
  FEATURE_SEGMENT: 'FeatureSegment',
  FIELD_RECORD_QUALITY_REVIEW: 'FieldRecordQualityReview',
  FIND: 'Find',
  FIND_COLLECTION: 'FindCollection',
  LAYER: 'Layer',
  OPERATION: 'Operation',
  PEN_MEMO: 'PenMemo',
  PHOTO: 'Photo',
  PLACE: 'Place',
  SAMPLE: 'Sample',
  SOIL_PROFILE_PHOTO: 'SoilProfilePhoto',
  SOURCE_EVIDENCE_INDEX: 'SourceEvidenceIndex',
  SURVEY: 'Survey',
  SURVEY_BOUNDARY: 'SurveyBoundary',
  TRENCH: 'Trench',
} as const;

export const FEATURE_CANDIDATE_PARENT_CATEGORIES: ReadonlyArray<string> = [
  KOREAN_FIELDWORK_CATEGORIES.OPERATION,
  KOREAN_FIELDWORK_CATEGORIES.TRENCH,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_GROUP,
];

export const FEATURE_WORKFLOW_CATEGORIES: ReadonlyArray<string> = [
  KOREAN_FIELDWORK_CATEGORIES.FEATURE,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_SEGMENT,
];

export const SOIL_PROFILE_PHOTO_TARGET_CATEGORIES: ReadonlyArray<string> = [
  KOREAN_FIELDWORK_CATEGORIES.OPERATION,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_SEGMENT,
];

export const KOREAN_FIELDWORK_CATEGORY_ORDER: ReadonlyArray<string> = [
  KOREAN_FIELDWORK_CATEGORIES.OPERATION,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE,
  KOREAN_FIELDWORK_CATEGORIES.TRENCH,
  KOREAN_FIELDWORK_CATEGORIES.LAYER,
  KOREAN_FIELDWORK_CATEGORIES.SURVEY,
  KOREAN_FIELDWORK_CATEGORIES.SURVEY_BOUNDARY,
  KOREAN_FIELDWORK_CATEGORIES.FIND,
  KOREAN_FIELDWORK_CATEGORIES.FIND_COLLECTION,
  KOREAN_FIELDWORK_CATEGORIES.SAMPLE,
  KOREAN_FIELDWORK_CATEGORIES.DRAWING,
  KOREAN_FIELDWORK_CATEGORIES.PHOTO,
  KOREAN_FIELDWORK_CATEGORIES.SOIL_PROFILE_PHOTO,
  KOREAN_FIELDWORK_CATEGORIES.AERIAL_MAP_LAYER,
  KOREAN_FIELDWORK_CATEGORIES.PEN_MEMO,
  KOREAN_FIELDWORK_CATEGORIES.DAILY_LOG,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_GROUP,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_SEGMENT,
  KOREAN_FIELDWORK_CATEGORIES.FIELD_RECORD_QUALITY_REVIEW,
  KOREAN_FIELDWORK_CATEGORIES.SOURCE_EVIDENCE_INDEX,
  KOREAN_FIELDWORK_CATEGORIES.PLACE,
];
