export const KOREAN_FIELDWORK_CATEGORIES = {
  AERIAL_MAP_LAYER: 'AerialMapLayer',
  DAILY_LOG: 'DailyLog',
  DRAWING: 'Drawing',
  FEATURE: 'Feature',
  FEATURE_GROUP: 'FeatureGroup',
  FEATURE_SEGMENT: 'FeatureSegment',
  FIELD_RECORD_QUALITY_REVIEW: 'FieldRecordQualityReview',
  FIND: 'Find',
  FIND_COLLECTION: 'FindCollection',
  LAYER: 'Layer',
  OPERATION: 'Operation',
  PEN_MEMO: 'PenMemo',
  PHOTO: 'Photo',
  PLACE: 'Place',
  SAMPLE: 'Sample',
  SOIL_PROFILE_PHOTO: 'SoilProfilePhoto',
  SOURCE_EVIDENCE_INDEX: 'SourceEvidenceIndex',
  SURVEY: 'Survey',
  SURVEY_BOUNDARY: 'SurveyBoundary',
  TRENCH: 'Trench',
} as const;

export const KOREAN_FIELDWORK_CATEGORY_LABELS: Readonly<Record<string, string>> = {
  [KOREAN_FIELDWORK_CATEGORIES.AERIAL_MAP_LAYER]: '항공 지도 레이어',
  [KOREAN_FIELDWORK_CATEGORIES.DAILY_LOG]: '작업일지',
  [KOREAN_FIELDWORK_CATEGORIES.DRAWING]: '도면',
  [KOREAN_FIELDWORK_CATEGORIES.FEATURE]: '유구',
  [KOREAN_FIELDWORK_CATEGORIES.FEATURE_GROUP]: '유구군',
  [KOREAN_FIELDWORK_CATEGORIES.FEATURE_SEGMENT]: '피트·유구 구간',
  [KOREAN_FIELDWORK_CATEGORIES.FIELD_RECORD_QUALITY_REVIEW]: '기록 보완 점검',
  [KOREAN_FIELDWORK_CATEGORIES.FIND]: '유물',
  [KOREAN_FIELDWORK_CATEGORIES.FIND_COLLECTION]: '유물 일괄',
  [KOREAN_FIELDWORK_CATEGORIES.LAYER]: '층위',
  [KOREAN_FIELDWORK_CATEGORIES.OPERATION]: '조사구역',
  [KOREAN_FIELDWORK_CATEGORIES.PEN_MEMO]: '펜메모',
  [KOREAN_FIELDWORK_CATEGORIES.PHOTO]: '사진',
  [KOREAN_FIELDWORK_CATEGORIES.PLACE]: '유적/지점',
  [KOREAN_FIELDWORK_CATEGORIES.SAMPLE]: '시료',
  [KOREAN_FIELDWORK_CATEGORIES.SOIL_PROFILE_PHOTO]: '토층 단면 사진',
  [KOREAN_FIELDWORK_CATEGORIES.SOURCE_EVIDENCE_INDEX]: '원문 근거 색인',
  [KOREAN_FIELDWORK_CATEGORIES.SURVEY]: '지표조사',
  [KOREAN_FIELDWORK_CATEGORIES.SURVEY_BOUNDARY]: '조사경계',
  [KOREAN_FIELDWORK_CATEGORIES.TRENCH]: '트렌치',
};

export const KOREAN_FIELDWORK_CATEGORY_DESCRIPTIONS: Readonly<Record<string, string>> = {
  [KOREAN_FIELDWORK_CATEGORIES.AERIAL_MAP_LAYER]: '드론 정사영상, 기준 배경지도, 현장 보정용 레이어를 남깁니다.',
  [KOREAN_FIELDWORK_CATEGORIES.DAILY_LOG]: '오늘의 작업 범위, 담당자, 관찰 내용과 변경사항을 묶습니다.',
  [KOREAN_FIELDWORK_CATEGORIES.DRAWING]: '실측도, 분포도, 보정 도면 등 도면 증거를 연결합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.FEATURE]: '수혈, 주거지, 목책, 구상유구처럼 개별 유구를 기록합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.FEATURE_GROUP]: '목책열, 수혈군, 건물지군처럼 함께 해석되는 유구 묶음입니다.',
  [KOREAN_FIELDWORK_CATEGORIES.FEATURE_SEGMENT]: '피트, 절개 구간, 내부 퇴적처럼 유구 안에서 따로 조사한 세부 단위입니다.',
  [KOREAN_FIELDWORK_CATEGORIES.FIELD_RECORD_QUALITY_REVIEW]: '마감 전 누락, 관찰·해석, 보고서 연결 상태를 점검합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.FIND]: '개별 유물의 출토 맥락, 수습 상태, 해석 근거를 기록합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.FIND_COLLECTION]: '동일 맥락의 유물 일괄 수습 또는 묶음 기록입니다.',
  [KOREAN_FIELDWORK_CATEGORIES.LAYER]: '토층 번호, 층 경계, 토색·토성을 기록합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.OPERATION]: '현장 조사구역, 조사 단위, 구역 경계의 기준 기록입니다.',
  [KOREAN_FIELDWORK_CATEGORIES.PEN_MEMO]: '태블릿에서 바로 적는 손글씨 메모와 전사 상태를 남깁니다.',
  [KOREAN_FIELDWORK_CATEGORIES.PHOTO]: '현장 사진, 유물 사진, 보고서용 사진 근거를 연결합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.SAMPLE]: '토양, 목탄, 유기물, 자연과학 분석용 시료를 기록합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.SOIL_PROFILE_PHOTO]: '토층 단면 사진과 층위 표시, 토색 보조 기록을 연결합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.SOURCE_EVIDENCE_INDEX]: '보고서·문헌·원자료 근거를 나중에 추적할 수 있게 색인합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.SURVEY]: '지표조사, 시굴 전 단계, 조사 방법과 관찰 조건을 기록합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.SURVEY_BOUNDARY]: '조사 범위, 구역선, 배경지도 출처와 정확도를 기록합니다.',
  [KOREAN_FIELDWORK_CATEGORIES.TRENCH]: '시굴·발굴 트렌치의 위치와 범위를 잡습니다.',
};

export const KOREAN_FIELDWORK_HIDDEN_ADD_CATEGORIES: readonly string[] = [
  'Image',
  'Process',
  'Project',
  'StoragePlace',
  'Type',
  'TypeCatalog',
  KOREAN_FIELDWORK_CATEGORIES.PLACE,
];

export const FEATURE_CANDIDATE_PARENT_CATEGORIES: readonly string[] = [
  KOREAN_FIELDWORK_CATEGORIES.OPERATION,
  KOREAN_FIELDWORK_CATEGORIES.TRENCH,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_GROUP,
];

export const FEATURE_WORKFLOW_CATEGORIES: readonly string[] = [
  KOREAN_FIELDWORK_CATEGORIES.FEATURE,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_SEGMENT,
];

export const SOIL_PROFILE_PHOTO_TARGET_CATEGORIES: readonly string[] = [
  KOREAN_FIELDWORK_CATEGORIES.OPERATION,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_SEGMENT,
];

export const KOREAN_FIELDWORK_CATEGORY_ORDER: readonly string[] = [
  KOREAN_FIELDWORK_CATEGORIES.OPERATION,
  KOREAN_FIELDWORK_CATEGORIES.TRENCH,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_GROUP,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE,
  KOREAN_FIELDWORK_CATEGORIES.FEATURE_SEGMENT,
  KOREAN_FIELDWORK_CATEGORIES.LAYER,
  KOREAN_FIELDWORK_CATEGORIES.SURVEY,
  KOREAN_FIELDWORK_CATEGORIES.SURVEY_BOUNDARY,
  KOREAN_FIELDWORK_CATEGORIES.FIND,
  KOREAN_FIELDWORK_CATEGORIES.FIND_COLLECTION,
  KOREAN_FIELDWORK_CATEGORIES.SAMPLE,
  KOREAN_FIELDWORK_CATEGORIES.DRAWING,
  KOREAN_FIELDWORK_CATEGORIES.PHOTO,
  KOREAN_FIELDWORK_CATEGORIES.SOIL_PROFILE_PHOTO,
  KOREAN_FIELDWORK_CATEGORIES.AERIAL_MAP_LAYER,
  KOREAN_FIELDWORK_CATEGORIES.PEN_MEMO,
  KOREAN_FIELDWORK_CATEGORIES.DAILY_LOG,
  KOREAN_FIELDWORK_CATEGORIES.FIELD_RECORD_QUALITY_REVIEW,
  KOREAN_FIELDWORK_CATEGORIES.SOURCE_EVIDENCE_INDEX,
  KOREAN_FIELDWORK_CATEGORIES.PLACE,
];

export const getKoreanFieldworkCategoryLabel = (
  categoryName: string
): string => KOREAN_FIELDWORK_CATEGORY_LABELS[categoryName] ?? categoryName;

export const getKoreanFieldworkCategoryDescription = (
  categoryName: string
): string => KOREAN_FIELDWORK_CATEGORY_DESCRIPTIONS[categoryName] ?? '현장 기록에 필요한 세부 정보를 이어서 입력합니다.';
