export const SAMPLE_DATA_LABELS = {
    'de': {
        'testProject': 'Testprojekt',
        'testCampaign': 'Testkampagne',
        'person': 'Person',
        'trench': 'Schnitt',
        'trenchShort': 'S',
        'stratigraphicalUnit': 'Stratigraphische Einheit',
        'stratigraphicalUnitShort': 'SE',
        'layer': 'Erdbefund',
        'architecture': 'Architektur',
        'grave': 'Grab',
        'findShort': 'F',
        'coin': 'Münze',
        'testFind': 'Testfund',
        'testFindShort': 'testf',
        'surveyArea': 'Survey-Areal',
        'surveyAreaShort': 'A',
        'surveyUnit': 'Planquadrat',
        'surveyUnitShort': 'PQ',
        'stone': 'Stein',
        'stoneShort': 'ST',
        'building': 'Gebäude',
        'buildingShort': 'B',
        'room': 'Raum',
        'roomShort': 'R',
    },
    'en': {
        'testProject': 'Test project',
        'testCampaign': 'Test campaign',
        'person': 'Person',
        'trench': 'Trench',
        'trenchShort': 'T',
        'stratigraphicalUnit': 'Stratrigraphical unit',
        'stratigraphicalUnitShort': 'SU',
        'layer': 'Layer',
        'architecture': 'Architecture',
        'grave': 'Grave',
        'findShort': 'F',
        'coin': 'Coin',
        'testFind': 'Test find',
        'testFindShort': 'testf',
        'surveyArea': 'Survey area',
        'surveyAreaShort': 'A',
        'surveyUnit': 'Survey unit',
        'surveyUnitShort': 'SUR',
        'stone': 'Stone',
        'stoneShort': 'ST',
        'building': 'Building',
        'buildingShort': 'B',
        'room': 'Room',
        'roomShort': 'R',
    }
};
