package org.dainst.idaifield;

/**
 * @author Thomas Kleinke
 */
public enum ErrorMessage {

    CONVERTER_UNSUPPORTED_GEOMETRY_TYPE,
    CONVERTER_SHAPEFILE_READ_ERROR,
    CONVERTER_JSONL_WRITE_ERROR,
    EXPORTER_TEMP_FOLDER_CREATION_ERROR,
    EXPORTER_ZIP_FILE_WRITE_ERROR,
    EXPORTER_SHAPEFILE_WRITE_ERROR,
    DATASTORE_GET_RESOURCES_ERROR
}
