version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    environment:
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms640m -Xmx640m"
      - "discovery.type=single-node"
      - "cluster.name=field.dainst.org"
      - "indices.query.bool.max_clause_count=4096"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data"

  cantaloupe:
    image: dainst/cantaloupe
    build: .
    ports:
      - 8182:8182
    environment:
      HTTP_HTTP2_ENABLED: "true"
      HTTPS_HTTP2_ENABLED: "true"
      ENDPOINT_IIIF_CONTENT_DISPOSITION: none
      SOURCE_STATIC: FilesystemSource
      FILESYSTEMSOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX: /imageroot/
      PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
      PROCESSOR_MANUALSELECTIONSTRATEGY_JP2: OpenJpegProcessor
      LOG_APPLICATION_LEVEL: warn
      LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
    volumes:
      - type: volume
        source: idai-field-web_images
        target: /imageroot
        volume:
          nocopy: true

  api:
    image: "ghcr.io/dainst/idai-field-web-api:latest"
    ports:
      - "4000:4000"
    volumes:
      - "/opt/idai-field/api/config:/opt/src/api/config"
      - "imagemagick-configs:/etc/ImageMagick-6"
      - type: volume
        source: idai-field-web_images
        target: /imageroot
        volume:
           nocopy: true
    networks:
      - web
      - default
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:field.idai.world; PathPrefix:/api"
        - "traefik.port=4000"

  ui:
    image: "ghcr.io/dainst/idai-field-web-ui:latest"
    networks:
      - web
      - default
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:field.idai.world,field.dainst.org"
        - "traefik.frontend.redirect.regex=^https://field.dainst.org(.*)"
        - "traefik.frontend.redirect.replacement=https://field.idai.world$${1}"
        - "traefik.frontend.redirect.permanent=true"
        - "traefik.port=80"
  anubis:
    image: ghcr.io/techarohq/anubis:v1.26.2
    restart: unless-stopped
    environment:
      TARGET: " "
      BIND: ":8080"
      REDIRECT_DOMAINS: field.idai.world
      PUBLIC_URL: "https://anubis.field.idai.world"
      COOKIE_DOMAIN: field.idai.world
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
    volumes:
      - "./botPolicy.yaml:/data/cfg/botPolicy.yaml:ro"
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.anubis.rule=Host(`anubis.field.idai.world`)
      - traefik.http.routers.anubis.entrypoints=websecure
      - traefik.http.routers.anubis.tls.certresolver=letsencrypt
      - traefik.http.services.anubis.loadbalancer.server.port=8080 # Telling Traefik where to receive requests
      - traefik.http.routers.anubis.service=anubis # Telling Traefik to use the above specified port
  traefik:
    image: "traefik:v3.6"
    container_name: traefik
    ports:
      #- "80:80"
      - "443:443"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.anubis.forwardauth.address=http://anubis:8080/.within.website/x/cmd/anubis/api/check
      - traefik.http.middlewares.realip.headers.customRequestHeaders.X-Forwarded-For=>CF-Connecting-IP
   
volumes:
  elasticsearch-data:
  idai-field-web_images:
    external: true
  imagemagick-configs:

networks:
  web:
    external: true
