version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    environment:
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms640m -Xmx640m"
      - "discovery.type=single-node"
      - "cluster.name=field.dainst.org"
      - "cluster.routing.allocation.disk.watermark.low=2gb"
      - "cluster.routing.allocation.disk.watermark.high=1gb"
      - "cluster.routing.allocation.disk.watermark.flood_stage=500mb"
      - "indices.query.bool.max_clause_count=4096"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"

  cantaloupe:
    image: "dainst/cantaloupe"
    ports:
      - "8182:8182"
    volumes:
      - "./data/cantaloupe:/imageroot"
    environment:
      HTTP_HTTP2_ENABLED: "true"
      HTTPS_HTTP2_ENABLED: "true"
      ENDPOINT_IIIF_CONTENT_DISPOSITION: none
      SOURCE_STATIC: FilesystemSource
      FILESYSTEMSOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX: /imageroot/
      PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
      PROCESSOR_MANUALSELECTIONSTRATEGY_JP2: OpenJpegProcessor
      LOG_APPLICATION_LEVEL: warn
      LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"

  api:
    image: "ghcr.io/dainst/idai-field-web-api:latest"
    build: "./api"
    ports:
      - "4000:4000"
    volumes:
      - "./api/config:/opt/src/api/config"
      - "./api/resources:/opt/src/api/resources"
      - "./api/lib:/opt/src/api/lib"
      - "./api/test:/opt/src/api/test"
      - "./api/assets:/opt/src/api/assets"
      - "./api/_build:/opt/src/api/_build"
      - "./data/cantaloupe:/imageroot"
      - "./imagemagick:/etc/ImageMagick-6"
      - "../core:/opt/src/api/assets/js/node_modules/idai-field-core"

  ui:
    image: "ghcr.io/dainst/idai-field-web-ui:latest"
    build: "./ui"
    ports:
      - "3002:80"
    volumes:
      - "./ui/build:/usr/share/nginx/html"
